Update knowledge-submissions-past-wikipedia.md
instructlab/dev-docs pull request #105
Opened 2024-06-25 09:01 UTC by lhawthorn

Added new approved Knowledge submission data sources, updated status for several.

Updated documentation with new process to take in requested knowledge sources to be open a PR against this devdoc.

Related to issue #59 which should be closed once this PR is reviewed and merged.

2024-06-25 22:02 UTC, jjasghar commented
I helped out yoru linting issues, the spell check doesn't like a bunch of the words...i guess we'll need to add them to the spell checker now:
```
Cynefin
Knowlege
OpenStax
PLOS
Standup
butvis
io
```

2024-06-26 20:57 UTC, markstur commented on docs/knowledge-submissions-past-wikipedia.md
> +For the purposes of Knowlege submissions to the InstructLab project, data sourced from items in the `approved` category require no further vetting from the Triage and/or other Maintainer teams. Items
s/Knowlege/Knowledge/

2024-06-26 20:58 UTC, markstur commented on docs/knowledge-submissions-past-wikipedia.md
> +1. Work with our legal team to adjudicate. [@lhawthorn](https://github.com/lhawthorn) is currently the owner of this step, butvis happy to educate & empower other folks to do this work.
typo s/butvis/but is/

2024-06-27 07:35 UTC, lhawthorn commented
LH is unaware of the existence of a Mergify dashboard and will get educated when maintainer team is online.

2024-06-27 07:38 UTC, lhawthorn commented
@mergifyio rebase

2024-06-27 17:31 UTC, markstur approved these changes
LGTM

2024-07-01 12:11 UTC, bjhargrave requested changes

2024-07-01 12:11 UTC, bjhargrave commented on docs/knowledge-submissions-past-wikipedia.md
> +- `reviewed - manually verify`: Legal team has reviewed this domain and while much of its source material meets our open licensing criteria, not all of it does. Each submission from this source must
```suggestion
- `reviewed - manually verify`: Legal team has reviewed this domain and while much of its source material meets our open licensing criteria, not all of it does. Each submission from this source must be manually verified to actually be under an appropriate content license or definitively in the public domain.
```

2024-07-01 12:11 UTC, bjhargrave commented on docs/knowledge-submissions-past-wikipedia.md
> +- Approved sources: <https://github.com/instructlab/taxonomy/blob/main/docs/KNOWLEDGE_GUIDE.md#accepted-knowledge>
```suggestion
- [Approved sources][approved]
```

2024-07-01 12:11 UTC, bjhargrave commented on docs/knowledge-submissions-past-wikipedia.md
> +- Rejected sources: <https://github.com/instructlab/taxonomy/blob/main/docs/KNOWLEDGE_GUIDE.md#avoid-these-topics>
```suggestion
- [Rejected sources][avoided]
```

2024-07-01 14:04 UTC, nathan-weinberg approved these changes
Pending @bjhargrave's comments this LGTM

2024-07-02 13:52 UTC, hickeyma commented on docs/knowledge-submissions-past-wikipedia.md
> +- `reviewed - manually verify`: Legal team has reviewed this domain and while much of its source material meets our open licensing criteria, not all of it does. Each submission from this source must
Updated

2024-07-02 13:52 UTC, bjhargrave commented
@hickeyma Your fix commit is not pushed to this PR. It is just in your fork.

2024-07-02 13:53 UTC, hickeyma approved these changes
LGTM thanks @lhawthorn  for the update of the updates. 

@bjhargrave Added your suggestions. Do you mind doing a quick review?

2024-07-02 13:54 UTC, hickeyma commented
Shoot, I see that @bjhargrave. Let me try and fix that.

2024-07-02 14:23 UTC, hickeyma commented
Thanks @bjhargrave for the help with the initial commit. Ready for review now.

2024-07-02 14:33 UTC, bjhargrave approved these changes

2024-07-02 16:03 UTC, merged