ADR for IBM Granite Embeddings
instructlab/dev-docs pull request #169
Opened 2024-12-20 15:46 UTC by jwm4

See also https://github.com/instructlab/dev-docs/pull/168 for the proposal to add an `adrs` directory and for the new ADR template being proposed.  I am complying with that proposed new directory structure and template for now, and will revise this ADR if the template or directory structure change during the review of that ADR.

2025-01-03 16:06 UTC, anastasds commented on docs/rag/adrs/granite-embeddings.md
> +InstructLab is already using IBM Granite generative models as default options for model training.  Using an IBM Granite embedding model extends both the advantages and disadvantages of depending on m
In keeping with the spirit of the template of making things easy to scan and read, can we reorganize this into a bulleted list? One example might be:

```
* We will have consistency with usage of IBM models when possible.
* We should consider strategies of offsetting perception of prioritizing IBM models over the needs of the product in addition to the clear motivation described here, such as in documentation.
* Users will be able to rely on IBM's outstanding, well-earned reputation for respecting intellectual property rights and careful compliance with legal restrictions.
```

2025-01-07 14:09 UTC, anastasds approved these changes

2025-01-10 19:40 UTC, jwm4 commented
I received some comments about this proposal in a direct message from @akashgit .  The pull request is updated with additional text to address the concerns that he raised.

2025-01-10 19:53 UTC, anastasds approved these changes

2025-01-10 20:22 UTC, hemajv approved these changes

2025-01-10 22:43 UTC, jwm4 commented
@instructlab/oversight-committee , this has approval from relevant stakeholders and no request for more changes so I think it is ready for final oversight now.  Can someone review this and if it meets the criteria merge it too?

2025-01-17 23:33 UTC, danmcp requested changes
Please squash commits to remove the intermediate changes

2025-01-17 23:41 UTC, jwm4 commented
Squashing is complete.

2025-01-18 00:09 UTC, danmcp commented
@jwm4 Re:

>I received some comments about this proposal in a direct message from @akashgit . The pull request is updated with additional text to address the concerns that he raised.

Are you confident these concerns were addressed or do we need @akashgit to re-review?

2025-01-18 01:18 UTC, jwm4 commented
> > I received some comments about this proposal in a direct message from @akashgit . The pull request is updated with additional text to address the concerns that he raised.
> 
> Are you confident these concerns were addressed or do we need @akashgit to re-review?

@akashgit was clear that he doesn't want to be the blocker, so I don't think we need to wait for a re-review.  I let him know on January 9 that I had updated the text to address the issues he raised, so if he wanted to submit a formal review in github, I think he would have by now.

He is concerned that we don't have enough data to be really data driven on this issue.  I agree with that assessment and I updated the Consequences section to be more explicit about the risk that we will need to pivot to another default as more data emerges.  I think that's an acceptable risk because changing the default embedding model is a fairly low cost operation.

I think it is time to make a decision now for what we will do now and then pivot later if it becomes clear that there are better options available.  I also think assessing the trade-offs between issues like hardware requirements, accuracy, IP/legal risk, etc. will always be very subjective.  I am hoping the "key considerations" listed in this document will provide a framework for making these subjective judgements long after the specific decision about which model is the best one for January 2025 has become irrelevant.

2025-01-18 01:23 UTC, danmcp approved these changes
Thanks for the explanation!

2025-01-18 01:33 UTC, merged