confluence design notes
instructlab/dev-docs pull request #64
Opened 2024-05-25 16:13 UTC by makelinux

2024-05-28 12:36 UTC, bjhargrave requested changes

2024-05-28 12:40 UTC, makelinux commented on docs/confluence-doc-source.md
> +
[Here is PR of the shema](https://github.com/instructlab/schema/pull/17)

2024-06-19 10:06 UTC, leseb commented
@makelinux could you please address @bjhargrave's comments so we can move forward? Thanks!

2024-07-03 13:35 UTC, hickeyma requested changes

2024-07-03 13:35 UTC, hickeyma commented on docs/confluence-doc-source.md
> +feature for fine-tuning models on internal documentation.
@makelinux Do you mind elaborating on why Confluence support is essential?

2024-07-17 09:29 UTC, makelinux commented on docs/confluence-doc-source.md
> +- [markdownify](https://pypi.org/project/markdownify/) –
Good question! I don't know.

2024-07-17 09:41 UTC, makelinux commented on docs/confluence-doc-source.md
> +Confluence credentials in config.yaml:
I've created empty https://instructlab.atlassian.net/ in Atlassian Cloud for testing.

2025-02-20 02:00 UTC, closed without merging