Update trusted providers of github actions
instructlab/dev-docs pull request #83
Opened 2024-06-10 08:09 UTC by liranr23

Based on
https://github.com/instructlab/dev-docs/blob/main/docs/github-actions-use-policy.md#trusted-providers-of-github-actions, update the trusted providers of instructlab.

Related to https://github.com/instructlab/instructlab/issues/1218

2024-06-10 08:37 UTC, leseb requested changes

2024-06-10 08:37 UTC, leseb commented on docs/github-actions-providers.md
> +* `ludeeus/action-shellcheck@*` - Spellcheck action
```suggestion
* `ludeeus/action-shellcheck@*` - Shellcheck action
```

2024-06-10 08:42 UTC, liranr23 commented on docs/github-actions-providers.md
> +* `ludeeus/action-shellcheck@*` - Spellcheck action
Indeed, done.

2024-06-10 08:49 UTC, leseb reviewed
Sorry I missed that during the first review. Can you split your commits like this:

* remove the unused `spellcheck-github-actions`
* add newly supported actions (shellcheck, build-and-inspect-python-package and file-existence-action)

Thanks!

2024-06-10 09:05 UTC, leseb approved these changes
Thanks!

2024-06-10 09:12 UTC, liranr23 commented
@leseb I can't tell on which `Misspelled words` the spellcheck fails. i guess it's the shellcheck. do you wish me to add it to the dictionary?

2024-06-10 09:23 UTC, leseb commented
> @leseb I can't tell on which `Misspelled words` the spellcheck fails. i guess it's the shellcheck. do you wish me to add it to the dictionary?

Yes it is:

```
Misspelled words:
<context> docs/github-actions-providers.md
--------------------------------------------------------------------------------
Shellcheck
```

Please add it to `.spellcheck-en-custom.txt` and run `make spellcheck-sort`.
Thanks!

2024-06-10 16:53 UTC, liranr23 commented on docs/github-actions-providers.md
> -* `rojopolis/spellcheck-github-actions@*` - Spellcheck action
I went only with instructlab repo, but e.g here (dev-docs), it is in use. i think now that it should stay(if you confirm it's global)

2024-06-10 18:04 UTC, russellb commented on docs/github-actions-providers.md
> -* `rojopolis/spellcheck-github-actions@*` - Spellcheck action
This doc specifies a policy for all instructlab repos

2024-06-11 08:35 UTC, leseb approved these changes
Approving again based on @russellb's suggestion. Thanks!

2024-06-11 15:03 UTC, bjhargrave approved these changes

2024-06-11 15:31 UTC, merged