InstructLab App proposal
instructlab/dev-docs pull request #94
Opened 2024-06-13 21:37 UTC by jjasghar

This is a proposal for creating a InstructLab Application

2024-06-14 07:41 UTC, leseb requested changes
I’m okay with the idea. Anything that can ease the adoption and improve the user experience is great. Thanks for working on this! Just a few nits.


Next time, could you push to your personal fork instead of pushing directly to the "instructlab" remote? It’s cluttering the [branches](https://github.com/instructlab/dev-docs/branches). We prefer to keep the branches clean, showing only "main" or release branches, rather than in-progress work. Thanks!

2024-06-14 07:41 UTC, leseb commented on docs/instructlab-app.md
> +# InstructLab App
```suggestion
# InstructLab macOS App
```

2024-06-14 07:41 UTC, leseb commented on docs/instructlab-app.md
> +This document is targeted for Mac applications, but the idea could easily be transferred to other operating systems.
```suggestion
This document is targeted for macOS applications, but the idea could easily be transferred to other operating systems.
```

2024-06-14 07:41 UTC, leseb commented on docs/instructlab-app.md
> +[ollama][ollama] has a Mac application that is a double click installation for their server to run the commands
```suggestion
[ollama][ollama] has a macOS application that is a double-click installation for their server to run the commands
```

2024-06-14 07:41 UTC, leseb commented on docs/instructlab-app.md
> +to have a model open to ask a `-qq` question to the local model, and even an ability to open up a "long running"
```suggestion
to have a model open to ask a quick question to the local model, and even an ability to open up a "long-running"
```

2024-06-14 07:41 UTC, leseb commented on docs/instructlab-app.md
> +2. Create an option to do a `-qq` to the via the drop down
```suggestion
2. Create an option to ask a quick question (`-qq` option) to the via the drop-down
```

2024-06-17 07:50 UTC, leseb requested changes
Just nits, missed those during my initial review, almost there thanks!

2024-06-17 07:50 UTC, leseb commented on docs/instructlab-app.md
> +locally. We propose creating the same "system bar" application, with the ability to run `ilab serve` in the background
```suggestion
locally. We propose creating the same "system bar" application, with the ability to run `ilab model serve` in the background
```

2024-06-17 07:50 UTC, leseb commented on docs/instructlab-app.md
> +and a possible way to do `ilab chat` from said application.
```suggestion
and a possible way to do `ilab model chat` from said application.
```

2024-06-17 07:50 UTC, leseb commented on docs/instructlab-app.md
> +Having the `ilab` dog up in the system bar telling you that `ilab serve` is running, could open up the opportunity
```suggestion
Having the `ilab` dog up in the system bar telling you that `ilab model serve` is running, could open up the opportunity
```

2024-06-17 07:50 UTC, leseb commented on docs/instructlab-app.md
> +1. Create a simple MVP of starting the `ilab serve` application, with controls for the `serve` options, including
```suggestion
1. Create a simple MVP of starting the `ilab model serve` application, with controls for the `serve` options, including
```

2024-06-17 07:50 UTC, leseb commented on docs/instructlab-app.md
> +3. Create a `ilab chat` type interface via a window or web browser.
```suggestion
3. Create a `ilab model chat` type interface via a window or web browser.
```

2024-06-17 18:33 UTC, leseb approved these changes
Thanks!

2024-06-18 09:28 UTC, merged

2024-06-28 15:33 UTC, jjasghar commented
For my future self: https://medium.com/@jackhuang.wz/in-just-two-steps-you-can-turn-a-python-script-into-a-macos-application-installer-6e21bce2ee71